#!/bin/sh
ssh ubuntu@172.31.41.190 <<EOF
    sudo curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.1/install.sh | bash
    source ~/.bash_profile
    nvm install 16.16.0
    cd frisklog-server
    npm install
    npm install -g pm2
    npm run pre-build
    npm run build
    npm run start
    exit
EOF