#!/bin/sh
ssh ubuntu@172.31.41.190 <<EOF
    cd ~/frisklog-server
    git pull
    curl -sL https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.0/install.sh -o install_nvm.sh | bash install_nvm.sh
    nvm install --lts
    npm install
    npm install -g pm2
    pm2 stop frisklog-server
    npm run build
    pm2 restart frisklog-server
    exit
EOF